#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: QuestNotification

#include "Basic.hpp"

#include "UMG_structs.hpp"
#include "FortniteGame_structs.hpp"
#include "Engine_structs.hpp"
#include "CoreUObject_structs.hpp"


namespace SDK::Params
{

// Function QuestNotification.QuestNotification_C.BP_OnTimerSet
// 0x0001 (0x0001 - 0x0000)
struct QuestNotification_C_BP_OnTimerSet final
{
public:
	EAthenaChallengeTimerState                    TimerState;                                        // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(QuestNotification_C_BP_OnTimerSet) == 0x000001, "Wrong alignment on QuestNotification_C_BP_OnTimerSet");
static_assert(sizeof(QuestNotification_C_BP_OnTimerSet) == 0x000001, "Wrong size on QuestNotification_C_BP_OnTimerSet");
static_assert(offsetof(QuestNotification_C_BP_OnTimerSet, TimerState) == 0x000000, "Member 'QuestNotification_C_BP_OnTimerSet::TimerState' has a wrong offset!");

// Function QuestNotification.QuestNotification_C.ExecuteUbergraph_QuestNotification
// 0x03C8 (0x03C8 - 0x0000)
struct QuestNotification_C_ExecuteUbergraph_QuestNotification final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(class UObject* Loaded)>        K2Node_CreateDelegate_OutputDelegate;              // 0x0004(0x000C)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable;                                // 0x0010(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_11[0x3];                                       // 0x0011(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_1;            // 0x0014(0x000C)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              Temp_byte_Variable;                                // 0x0020(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              Temp_byte_Variable_1;                              // 0x0021(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable_1;                              // 0x0022(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable_2;                              // 0x0023(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              Temp_byte_Variable_2;                              // 0x0024(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              Temp_byte_Variable_3;                              // 0x0025(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_26[0x2];                                       // 0x0026(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	class UObject*                                K2Node_CustomEvent_Loaded_1;                       // 0x0028(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UObject*                                Temp_object_Variable;                              // 0x0030(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UMaterialInterface*                     K2Node_DynamicCast_AsMaterial_Interface;           // 0x0038(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0040(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_41[0x7];                                       // 0x0041(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UTexture2D*                             K2Node_DynamicCast_AsTexture_2D;                   // 0x0048(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_1;                     // 0x0050(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_51[0x7];                                       // 0x0051(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UObject*                                K2Node_CustomEvent_Loaded;                         // 0x0058(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UObject*                                Temp_object_Variable_1;                            // 0x0060(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UMaterialInterface*                     K2Node_DynamicCast_AsMaterial_Interface_1;         // 0x0068(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_2;                     // 0x0070(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_71[0x3];                                       // 0x0071(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_GetEndTime_ReturnValue;                   // 0x0074(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UUMGSequencePlayer*                     CallFunc_PlayAnimation_ReturnValue;                // 0x0078(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable_3;                              // 0x0080(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_GreaterEqual_IntInt_ReturnValue;          // 0x0081(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_82[0x6];                                       // 0x0082(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UMaterialInstanceDynamic*               CallFunc_GetDynamicMaterial_ReturnValue;           // 0x0088(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Conv_IntToDouble_ReturnValue;             // 0x0090(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Max_ReturnValue;                          // 0x0098(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_9C[0x4];                                       // 0x009C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_Conv_IntToDouble_ReturnValue_1;           // 0x00A0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UMaterialInstanceDynamic*               CallFunc_GetDynamicMaterial_ReturnValue_1;         // 0x00A8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Divide_DoubleDouble_ReturnValue;          // 0x00B0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_bWasAssisted;                         // 0x00B8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_B9[0x7];                                       // 0x00B9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 K2Node_Event_OtherPlayersName;                     // 0x00C0(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FText                                   CallFunc_Conv_StringToText_ReturnValue;            // 0x00D0(0x0018)()
	class FText                                   CallFunc_Conv_StringToText_ReturnValue_1;          // 0x00E8(0x0018)()
	struct FFormatArgumentData                    K2Node_MakeStruct_FormatArgumentData;              // 0x0100(0x0050)(HasGetValueTypeHash)
	struct FFormatArgumentData                    K2Node_MakeStruct_FormatArgumentData_1;            // 0x0150(0x0050)(HasGetValueTypeHash)
	TArray<struct FFormatArgumentData>            K2Node_MakeArray_Array;                            // 0x01A0(0x0010)(ReferenceParm)
	TArray<struct FFormatArgumentData>            K2Node_MakeArray_Array_1;                          // 0x01B0(0x0010)(ReferenceParm)
	class FText                                   CallFunc_Format_ReturnValue;                       // 0x01C0(0x0018)()
	class FText                                   CallFunc_Format_ReturnValue_1;                     // 0x01D8(0x0018)()
	EAthenaChallengeTimerState                    K2Node_Event_TimerState;                           // 0x01F0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1F1[0x3];                                      // 0x01F1(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FLinearColor                           Temp_struct_Variable;                              // 0x01F4(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue;          // 0x0204(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue_1;        // 0x0205(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_206[0x2];                                      // 0x0206(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	struct FLinearColor                           Temp_struct_Variable_1;                            // 0x0208(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UWidget*                                K2Node_Select_Default;                             // 0x0218(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	struct FLinearColor                           Temp_struct_Variable_2;                            // 0x0220(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FLinearColor                           Temp_struct_Variable_3;                            // 0x0230(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UUMGSequencePlayer*                     CallFunc_PlayAnimation_ReturnValue_1;              // 0x0240(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_GreaterEqual_IntInt_ReturnValue_1;        // 0x0248(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_249[0x3];                                      // 0x0249(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_GetEndTime_ReturnValue_1;                 // 0x024C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FLinearColor                           Temp_struct_Variable_4;                            // 0x0250(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_IsEnabled;                            // 0x0260(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_261[0x3];                                      // 0x0261(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         K2Node_Event_Rate;                                 // 0x0264(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TSoftObjectPtr<class UObject>                 K2Node_Event_AssetToDisplay;                       // 0x0268(0x0020)(ConstParm, UObjectWrapper, HasGetValueTypeHash)
	bool                                          K2Node_Event_bUseRarityContainer;                  // 0x0288(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_bIsDailyPunchcardQuest;               // 0x0289(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_28A[0x6];                                      // 0x028A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_FMax_ReturnValue;                         // 0x0290(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UUMGSequencePlayer*                     CallFunc_PlayAnimation_ReturnValue_2;              // 0x0298(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              K2Node_Select_Default_1;                           // 0x02A0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2A1[0x3];                                      // 0x02A1(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FLinearColor                           Temp_struct_Variable_5;                            // 0x02A4(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Temp_byte_Variable_4;                              // 0x02B4(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2B5[0x3];                                      // 0x02B5(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FLinearColor                           K2Node_Select_Default_2;                           // 0x02B8(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UWidget*                                K2Node_Select_Default_3;                           // 0x02C8(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_GreaterEqual_IntInt_ReturnValue_2;        // 0x02D0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2D1[0x7];                                      // 0x02D1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UMaterialInstanceDynamic*               CallFunc_GetDynamicMaterial_ReturnValue_2;         // 0x02D8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              K2Node_Select_Default_4;                           // 0x02E0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2E1[0x7];                                      // 0x02E1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   CallFunc_GetText_ReturnValue;                      // 0x02E8(0x0018)()
	bool                                          CallFunc_TextIsEmpty_ReturnValue;                  // 0x0300(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_301[0x7];                                      // 0x0301(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UUMGSequencePlayer*                     CallFunc_PlayAnimation_ReturnValue_3;              // 0x0308(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_2;            // 0x0310(0x000C)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_GreaterEqual_IntInt_ReturnValue_3;        // 0x031C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_31D[0x3];                                      // 0x031D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TSoftObjectPtr<class UObject>                 K2Node_CustomEvent_Asset;                          // 0x0320(0x0020)(HasGetValueTypeHash)
	TDelegate<void(class UObject* Loaded)>        K2Node_CreateDelegate_OutputDelegate_3;            // 0x0340(0x000C)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_34C[0x4];                                      // 0x034C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UMaterialInstanceDynamic*               CallFunc_GetDynamicMaterial_ReturnValue_3;         // 0x0350(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_IsDesignTime;                         // 0x0358(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_359[0x3];                                      // 0x0359(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_4;            // 0x035C(0x000C)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	TSoftObjectPtr<class UMaterialInterface>      K2Node_CustomEvent_SoftMaterial;                   // 0x0368(0x0020)(HasGetValueTypeHash)
	bool                                          CallFunc_PlayAnimationByName_ReturnValue;          // 0x0388(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_PlayAnimationByName_ReturnValue_1;        // 0x0389(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_38A[0x6];                                      // 0x038A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_Divide_DoubleDouble_ReturnValue_1;        // 0x0390(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_SetScalarParameterValue_Value_ImplicitCast; // 0x0398(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_SetScalarParameterValue_Value_ImplicitCast_1; // 0x039C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_FMax_A_ImplicitCast;                      // 0x03A0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_PlayAnimationByName_Speed_ImplicitCast;   // 0x03A8(0x0004)(ConstParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_PlayAnimation_PlaybackSpeed_ImplicitCast; // 0x03AC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_SetWidthOverride_InWidthOverride_ImplicitCast; // 0x03B0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3B4[0x4];                                      // 0x03B4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_Divide_DoubleDouble_A_ImplicitCast;       // 0x03B8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_RetriggerableDelay_Duration_ImplicitCast; // 0x03C0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(QuestNotification_C_ExecuteUbergraph_QuestNotification) == 0x000008, "Wrong alignment on QuestNotification_C_ExecuteUbergraph_QuestNotification");
static_assert(sizeof(QuestNotification_C_ExecuteUbergraph_QuestNotification) == 0x0003C8, "Wrong size on QuestNotification_C_ExecuteUbergraph_QuestNotification");
static_assert(offsetof(QuestNotification_C_ExecuteUbergraph_QuestNotification, EntryPoint) == 0x000000, "Member 'QuestNotification_C_ExecuteUbergraph_QuestNotification::EntryPoint' has a wrong offset!");
static_assert(offsetof(QuestNotification_C_ExecuteUbergraph_QuestNotification, K2Node_CreateDelegate_OutputDelegate) == 0x000004, "Member 'QuestNotification_C_ExecuteUbergraph_QuestNotification::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(QuestNotification_C_ExecuteUbergraph_QuestNotification, Temp_bool_Variable) == 0x000010, "Member 'QuestNotification_C_ExecuteUbergraph_QuestNotification::Temp_bool_Variable' has a wrong offset!");
static_assert(offsetof(QuestNotification_C_ExecuteUbergraph_QuestNotification, K2Node_CreateDelegate_OutputDelegate_1) == 0x000014, "Member 'QuestNotification_C_ExecuteUbergraph_QuestNotification::K2Node_CreateDelegate_OutputDelegate_1' has a wrong offset!");
static_assert(offsetof(QuestNotification_C_ExecuteUbergraph_QuestNotification, Temp_byte_Variable) == 0x000020, "Member 'QuestNotification_C_ExecuteUbergraph_QuestNotification::Temp_byte_Variable' has a wrong offset!");
static_assert(offsetof(QuestNotification_C_ExecuteUbergraph_QuestNotification, Temp_byte_Variable_1) == 0x000021, "Member 'QuestNotification_C_ExecuteUbergraph_QuestNotification::Temp_byte_Variable_1' has a wrong offset!");
static_assert(offsetof(QuestNotification_C_ExecuteUbergraph_QuestNotification, Temp_bool_Variable_1) == 0x000022, "Member 'QuestNotification_C_ExecuteUbergraph_QuestNotification::Temp_bool_Variable_1' has a wrong offset!");
static_assert(offsetof(QuestNotification_C_ExecuteUbergraph_QuestNotification, Temp_bool_Variable_2) == 0x000023, "Member 'QuestNotification_C_ExecuteUbergraph_QuestNotification::Temp_bool_Variable_2' has a wrong offset!");
static_assert(offsetof(QuestNotification_C_ExecuteUbergraph_QuestNotification, Temp_byte_Variable_2) == 0x000024, "Member 'QuestNotification_C_ExecuteUbergraph_QuestNotification::Temp_byte_Variable_2' has a wrong offset!");
static_assert(offsetof(QuestNotification_C_ExecuteUbergraph_QuestNotification, Temp_byte_Variable_3) == 0x000025, "Member 'QuestNotification_C_ExecuteUbergraph_QuestNotification::Temp_byte_Variable_3' has a wrong offset!");
static_assert(offsetof(QuestNotification_C_ExecuteUbergraph_QuestNotification, K2Node_CustomEvent_Loaded_1) == 0x000028, "Member 'QuestNotification_C_ExecuteUbergraph_QuestNotification::K2Node_CustomEvent_Loaded_1' has a wrong offset!");
static_assert(offsetof(QuestNotification_C_ExecuteUbergraph_QuestNotification, Temp_object_Variable) == 0x000030, "Member 'QuestNotification_C_ExecuteUbergraph_QuestNotification::Temp_object_Variable' has a wrong offset!");
static_assert(offsetof(QuestNotification_C_ExecuteUbergraph_QuestNotification, K2Node_DynamicCast_AsMaterial_Interface) == 0x000038, "Member 'QuestNotification_C_ExecuteUbergraph_QuestNotification::K2Node_DynamicCast_AsMaterial_Interface' has a wrong offset!");
static_assert(offsetof(QuestNotification_C_ExecuteUbergraph_QuestNotification, K2Node_DynamicCast_bSuccess) == 0x000040, "Member 'QuestNotification_C_ExecuteUbergraph_QuestNotification::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(QuestNotification_C_ExecuteUbergraph_QuestNotification, K2Node_DynamicCast_AsTexture_2D) == 0x000048, "Member 'QuestNotification_C_ExecuteUbergraph_QuestNotification::K2Node_DynamicCast_AsTexture_2D' has a wrong offset!");
static_assert(offsetof(QuestNotification_C_ExecuteUbergraph_QuestNotification, K2Node_DynamicCast_bSuccess_1) == 0x000050, "Member 'QuestNotification_C_ExecuteUbergraph_QuestNotification::K2Node_DynamicCast_bSuccess_1' has a wrong offset!");
static_assert(offsetof(QuestNotification_C_ExecuteUbergraph_QuestNotification, K2Node_CustomEvent_Loaded) == 0x000058, "Member 'QuestNotification_C_ExecuteUbergraph_QuestNotification::K2Node_CustomEvent_Loaded' has a wrong offset!");
static_assert(offsetof(QuestNotification_C_ExecuteUbergraph_QuestNotification, Temp_object_Variable_1) == 0x000060, "Member 'QuestNotification_C_ExecuteUbergraph_QuestNotification::Temp_object_Variable_1' has a wrong offset!");
static_assert(offsetof(QuestNotification_C_ExecuteUbergraph_QuestNotification, K2Node_DynamicCast_AsMaterial_Interface_1) == 0x000068, "Member 'QuestNotification_C_ExecuteUbergraph_QuestNotification::K2Node_DynamicCast_AsMaterial_Interface_1' has a wrong offset!");
static_assert(offsetof(QuestNotification_C_ExecuteUbergraph_QuestNotification, K2Node_DynamicCast_bSuccess_2) == 0x000070, "Member 'QuestNotification_C_ExecuteUbergraph_QuestNotification::K2Node_DynamicCast_bSuccess_2' has a wrong offset!");
static_assert(offsetof(QuestNotification_C_ExecuteUbergraph_QuestNotification, CallFunc_GetEndTime_ReturnValue) == 0x000074, "Member 'QuestNotification_C_ExecuteUbergraph_QuestNotification::CallFunc_GetEndTime_ReturnValue' has a wrong offset!");
static_assert(offsetof(QuestNotification_C_ExecuteUbergraph_QuestNotification, CallFunc_PlayAnimation_ReturnValue) == 0x000078, "Member 'QuestNotification_C_ExecuteUbergraph_QuestNotification::CallFunc_PlayAnimation_ReturnValue' has a wrong offset!");
static_assert(offsetof(QuestNotification_C_ExecuteUbergraph_QuestNotification, Temp_bool_Variable_3) == 0x000080, "Member 'QuestNotification_C_ExecuteUbergraph_QuestNotification::Temp_bool_Variable_3' has a wrong offset!");
static_assert(offsetof(QuestNotification_C_ExecuteUbergraph_QuestNotification, CallFunc_GreaterEqual_IntInt_ReturnValue) == 0x000081, "Member 'QuestNotification_C_ExecuteUbergraph_QuestNotification::CallFunc_GreaterEqual_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(QuestNotification_C_ExecuteUbergraph_QuestNotification, CallFunc_GetDynamicMaterial_ReturnValue) == 0x000088, "Member 'QuestNotification_C_ExecuteUbergraph_QuestNotification::CallFunc_GetDynamicMaterial_ReturnValue' has a wrong offset!");
static_assert(offsetof(QuestNotification_C_ExecuteUbergraph_QuestNotification, CallFunc_Conv_IntToDouble_ReturnValue) == 0x000090, "Member 'QuestNotification_C_ExecuteUbergraph_QuestNotification::CallFunc_Conv_IntToDouble_ReturnValue' has a wrong offset!");
static_assert(offsetof(QuestNotification_C_ExecuteUbergraph_QuestNotification, CallFunc_Max_ReturnValue) == 0x000098, "Member 'QuestNotification_C_ExecuteUbergraph_QuestNotification::CallFunc_Max_ReturnValue' has a wrong offset!");
static_assert(offsetof(QuestNotification_C_ExecuteUbergraph_QuestNotification, CallFunc_Conv_IntToDouble_ReturnValue_1) == 0x0000A0, "Member 'QuestNotification_C_ExecuteUbergraph_QuestNotification::CallFunc_Conv_IntToDouble_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(QuestNotification_C_ExecuteUbergraph_QuestNotification, CallFunc_GetDynamicMaterial_ReturnValue_1) == 0x0000A8, "Member 'QuestNotification_C_ExecuteUbergraph_QuestNotification::CallFunc_GetDynamicMaterial_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(QuestNotification_C_ExecuteUbergraph_QuestNotification, CallFunc_Divide_DoubleDouble_ReturnValue) == 0x0000B0, "Member 'QuestNotification_C_ExecuteUbergraph_QuestNotification::CallFunc_Divide_DoubleDouble_ReturnValue' has a wrong offset!");
static_assert(offsetof(QuestNotification_C_ExecuteUbergraph_QuestNotification, K2Node_Event_bWasAssisted) == 0x0000B8, "Member 'QuestNotification_C_ExecuteUbergraph_QuestNotification::K2Node_Event_bWasAssisted' has a wrong offset!");
static_assert(offsetof(QuestNotification_C_ExecuteUbergraph_QuestNotification, K2Node_Event_OtherPlayersName) == 0x0000C0, "Member 'QuestNotification_C_ExecuteUbergraph_QuestNotification::K2Node_Event_OtherPlayersName' has a wrong offset!");
static_assert(offsetof(QuestNotification_C_ExecuteUbergraph_QuestNotification, CallFunc_Conv_StringToText_ReturnValue) == 0x0000D0, "Member 'QuestNotification_C_ExecuteUbergraph_QuestNotification::CallFunc_Conv_StringToText_ReturnValue' has a wrong offset!");
static_assert(offsetof(QuestNotification_C_ExecuteUbergraph_QuestNotification, CallFunc_Conv_StringToText_ReturnValue_1) == 0x0000E8, "Member 'QuestNotification_C_ExecuteUbergraph_QuestNotification::CallFunc_Conv_StringToText_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(QuestNotification_C_ExecuteUbergraph_QuestNotification, K2Node_MakeStruct_FormatArgumentData) == 0x000100, "Member 'QuestNotification_C_ExecuteUbergraph_QuestNotification::K2Node_MakeStruct_FormatArgumentData' has a wrong offset!");
static_assert(offsetof(QuestNotification_C_ExecuteUbergraph_QuestNotification, K2Node_MakeStruct_FormatArgumentData_1) == 0x000150, "Member 'QuestNotification_C_ExecuteUbergraph_QuestNotification::K2Node_MakeStruct_FormatArgumentData_1' has a wrong offset!");
static_assert(offsetof(QuestNotification_C_ExecuteUbergraph_QuestNotification, K2Node_MakeArray_Array) == 0x0001A0, "Member 'QuestNotification_C_ExecuteUbergraph_QuestNotification::K2Node_MakeArray_Array' has a wrong offset!");
static_assert(offsetof(QuestNotification_C_ExecuteUbergraph_QuestNotification, K2Node_MakeArray_Array_1) == 0x0001B0, "Member 'QuestNotification_C_ExecuteUbergraph_QuestNotification::K2Node_MakeArray_Array_1' has a wrong offset!");
static_assert(offsetof(QuestNotification_C_ExecuteUbergraph_QuestNotification, CallFunc_Format_ReturnValue) == 0x0001C0, "Member 'QuestNotification_C_ExecuteUbergraph_QuestNotification::CallFunc_Format_ReturnValue' has a wrong offset!");
static_assert(offsetof(QuestNotification_C_ExecuteUbergraph_QuestNotification, CallFunc_Format_ReturnValue_1) == 0x0001D8, "Member 'QuestNotification_C_ExecuteUbergraph_QuestNotification::CallFunc_Format_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(QuestNotification_C_ExecuteUbergraph_QuestNotification, K2Node_Event_TimerState) == 0x0001F0, "Member 'QuestNotification_C_ExecuteUbergraph_QuestNotification::K2Node_Event_TimerState' has a wrong offset!");
static_assert(offsetof(QuestNotification_C_ExecuteUbergraph_QuestNotification, Temp_struct_Variable) == 0x0001F4, "Member 'QuestNotification_C_ExecuteUbergraph_QuestNotification::Temp_struct_Variable' has a wrong offset!");
static_assert(offsetof(QuestNotification_C_ExecuteUbergraph_QuestNotification, CallFunc_EqualEqual_ByteByte_ReturnValue) == 0x000204, "Member 'QuestNotification_C_ExecuteUbergraph_QuestNotification::CallFunc_EqualEqual_ByteByte_ReturnValue' has a wrong offset!");
static_assert(offsetof(QuestNotification_C_ExecuteUbergraph_QuestNotification, CallFunc_EqualEqual_ByteByte_ReturnValue_1) == 0x000205, "Member 'QuestNotification_C_ExecuteUbergraph_QuestNotification::CallFunc_EqualEqual_ByteByte_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(QuestNotification_C_ExecuteUbergraph_QuestNotification, Temp_struct_Variable_1) == 0x000208, "Member 'QuestNotification_C_ExecuteUbergraph_QuestNotification::Temp_struct_Variable_1' has a wrong offset!");
static_assert(offsetof(QuestNotification_C_ExecuteUbergraph_QuestNotification, K2Node_Select_Default) == 0x000218, "Member 'QuestNotification_C_ExecuteUbergraph_QuestNotification::K2Node_Select_Default' has a wrong offset!");
static_assert(offsetof(QuestNotification_C_ExecuteUbergraph_QuestNotification, Temp_struct_Variable_2) == 0x000220, "Member 'QuestNotification_C_ExecuteUbergraph_QuestNotification::Temp_struct_Variable_2' has a wrong offset!");
static_assert(offsetof(QuestNotification_C_ExecuteUbergraph_QuestNotification, Temp_struct_Variable_3) == 0x000230, "Member 'QuestNotification_C_ExecuteUbergraph_QuestNotification::Temp_struct_Variable_3' has a wrong offset!");
static_assert(offsetof(QuestNotification_C_ExecuteUbergraph_QuestNotification, CallFunc_PlayAnimation_ReturnValue_1) == 0x000240, "Member 'QuestNotification_C_ExecuteUbergraph_QuestNotification::CallFunc_PlayAnimation_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(QuestNotification_C_ExecuteUbergraph_QuestNotification, CallFunc_GreaterEqual_IntInt_ReturnValue_1) == 0x000248, "Member 'QuestNotification_C_ExecuteUbergraph_QuestNotification::CallFunc_GreaterEqual_IntInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(QuestNotification_C_ExecuteUbergraph_QuestNotification, CallFunc_GetEndTime_ReturnValue_1) == 0x00024C, "Member 'QuestNotification_C_ExecuteUbergraph_QuestNotification::CallFunc_GetEndTime_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(QuestNotification_C_ExecuteUbergraph_QuestNotification, Temp_struct_Variable_4) == 0x000250, "Member 'QuestNotification_C_ExecuteUbergraph_QuestNotification::Temp_struct_Variable_4' has a wrong offset!");
static_assert(offsetof(QuestNotification_C_ExecuteUbergraph_QuestNotification, K2Node_Event_IsEnabled) == 0x000260, "Member 'QuestNotification_C_ExecuteUbergraph_QuestNotification::K2Node_Event_IsEnabled' has a wrong offset!");
static_assert(offsetof(QuestNotification_C_ExecuteUbergraph_QuestNotification, K2Node_Event_Rate) == 0x000264, "Member 'QuestNotification_C_ExecuteUbergraph_QuestNotification::K2Node_Event_Rate' has a wrong offset!");
static_assert(offsetof(QuestNotification_C_ExecuteUbergraph_QuestNotification, K2Node_Event_AssetToDisplay) == 0x000268, "Member 'QuestNotification_C_ExecuteUbergraph_QuestNotification::K2Node_Event_AssetToDisplay' has a wrong offset!");
static_assert(offsetof(QuestNotification_C_ExecuteUbergraph_QuestNotification, K2Node_Event_bUseRarityContainer) == 0x000288, "Member 'QuestNotification_C_ExecuteUbergraph_QuestNotification::K2Node_Event_bUseRarityContainer' has a wrong offset!");
static_assert(offsetof(QuestNotification_C_ExecuteUbergraph_QuestNotification, K2Node_Event_bIsDailyPunchcardQuest) == 0x000289, "Member 'QuestNotification_C_ExecuteUbergraph_QuestNotification::K2Node_Event_bIsDailyPunchcardQuest' has a wrong offset!");
static_assert(offsetof(QuestNotification_C_ExecuteUbergraph_QuestNotification, CallFunc_FMax_ReturnValue) == 0x000290, "Member 'QuestNotification_C_ExecuteUbergraph_QuestNotification::CallFunc_FMax_ReturnValue' has a wrong offset!");
static_assert(offsetof(QuestNotification_C_ExecuteUbergraph_QuestNotification, CallFunc_PlayAnimation_ReturnValue_2) == 0x000298, "Member 'QuestNotification_C_ExecuteUbergraph_QuestNotification::CallFunc_PlayAnimation_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(QuestNotification_C_ExecuteUbergraph_QuestNotification, K2Node_Select_Default_1) == 0x0002A0, "Member 'QuestNotification_C_ExecuteUbergraph_QuestNotification::K2Node_Select_Default_1' has a wrong offset!");
static_assert(offsetof(QuestNotification_C_ExecuteUbergraph_QuestNotification, Temp_struct_Variable_5) == 0x0002A4, "Member 'QuestNotification_C_ExecuteUbergraph_QuestNotification::Temp_struct_Variable_5' has a wrong offset!");
static_assert(offsetof(QuestNotification_C_ExecuteUbergraph_QuestNotification, Temp_byte_Variable_4) == 0x0002B4, "Member 'QuestNotification_C_ExecuteUbergraph_QuestNotification::Temp_byte_Variable_4' has a wrong offset!");
static_assert(offsetof(QuestNotification_C_ExecuteUbergraph_QuestNotification, K2Node_Select_Default_2) == 0x0002B8, "Member 'QuestNotification_C_ExecuteUbergraph_QuestNotification::K2Node_Select_Default_2' has a wrong offset!");
static_assert(offsetof(QuestNotification_C_ExecuteUbergraph_QuestNotification, K2Node_Select_Default_3) == 0x0002C8, "Member 'QuestNotification_C_ExecuteUbergraph_QuestNotification::K2Node_Select_Default_3' has a wrong offset!");
static_assert(offsetof(QuestNotification_C_ExecuteUbergraph_QuestNotification, CallFunc_GreaterEqual_IntInt_ReturnValue_2) == 0x0002D0, "Member 'QuestNotification_C_ExecuteUbergraph_QuestNotification::CallFunc_GreaterEqual_IntInt_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(QuestNotification_C_ExecuteUbergraph_QuestNotification, CallFunc_GetDynamicMaterial_ReturnValue_2) == 0x0002D8, "Member 'QuestNotification_C_ExecuteUbergraph_QuestNotification::CallFunc_GetDynamicMaterial_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(QuestNotification_C_ExecuteUbergraph_QuestNotification, K2Node_Select_Default_4) == 0x0002E0, "Member 'QuestNotification_C_ExecuteUbergraph_QuestNotification::K2Node_Select_Default_4' has a wrong offset!");
static_assert(offsetof(QuestNotification_C_ExecuteUbergraph_QuestNotification, CallFunc_GetText_ReturnValue) == 0x0002E8, "Member 'QuestNotification_C_ExecuteUbergraph_QuestNotification::CallFunc_GetText_ReturnValue' has a wrong offset!");
static_assert(offsetof(QuestNotification_C_ExecuteUbergraph_QuestNotification, CallFunc_TextIsEmpty_ReturnValue) == 0x000300, "Member 'QuestNotification_C_ExecuteUbergraph_QuestNotification::CallFunc_TextIsEmpty_ReturnValue' has a wrong offset!");
static_assert(offsetof(QuestNotification_C_ExecuteUbergraph_QuestNotification, CallFunc_PlayAnimation_ReturnValue_3) == 0x000308, "Member 'QuestNotification_C_ExecuteUbergraph_QuestNotification::CallFunc_PlayAnimation_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(QuestNotification_C_ExecuteUbergraph_QuestNotification, K2Node_CreateDelegate_OutputDelegate_2) == 0x000310, "Member 'QuestNotification_C_ExecuteUbergraph_QuestNotification::K2Node_CreateDelegate_OutputDelegate_2' has a wrong offset!");
static_assert(offsetof(QuestNotification_C_ExecuteUbergraph_QuestNotification, CallFunc_GreaterEqual_IntInt_ReturnValue_3) == 0x00031C, "Member 'QuestNotification_C_ExecuteUbergraph_QuestNotification::CallFunc_GreaterEqual_IntInt_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(QuestNotification_C_ExecuteUbergraph_QuestNotification, K2Node_CustomEvent_Asset) == 0x000320, "Member 'QuestNotification_C_ExecuteUbergraph_QuestNotification::K2Node_CustomEvent_Asset' has a wrong offset!");
static_assert(offsetof(QuestNotification_C_ExecuteUbergraph_QuestNotification, K2Node_CreateDelegate_OutputDelegate_3) == 0x000340, "Member 'QuestNotification_C_ExecuteUbergraph_QuestNotification::K2Node_CreateDelegate_OutputDelegate_3' has a wrong offset!");
static_assert(offsetof(QuestNotification_C_ExecuteUbergraph_QuestNotification, CallFunc_GetDynamicMaterial_ReturnValue_3) == 0x000350, "Member 'QuestNotification_C_ExecuteUbergraph_QuestNotification::CallFunc_GetDynamicMaterial_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(QuestNotification_C_ExecuteUbergraph_QuestNotification, K2Node_Event_IsDesignTime) == 0x000358, "Member 'QuestNotification_C_ExecuteUbergraph_QuestNotification::K2Node_Event_IsDesignTime' has a wrong offset!");
static_assert(offsetof(QuestNotification_C_ExecuteUbergraph_QuestNotification, K2Node_CreateDelegate_OutputDelegate_4) == 0x00035C, "Member 'QuestNotification_C_ExecuteUbergraph_QuestNotification::K2Node_CreateDelegate_OutputDelegate_4' has a wrong offset!");
static_assert(offsetof(QuestNotification_C_ExecuteUbergraph_QuestNotification, K2Node_CustomEvent_SoftMaterial) == 0x000368, "Member 'QuestNotification_C_ExecuteUbergraph_QuestNotification::K2Node_CustomEvent_SoftMaterial' has a wrong offset!");
static_assert(offsetof(QuestNotification_C_ExecuteUbergraph_QuestNotification, CallFunc_PlayAnimationByName_ReturnValue) == 0x000388, "Member 'QuestNotification_C_ExecuteUbergraph_QuestNotification::CallFunc_PlayAnimationByName_ReturnValue' has a wrong offset!");
static_assert(offsetof(QuestNotification_C_ExecuteUbergraph_QuestNotification, CallFunc_PlayAnimationByName_ReturnValue_1) == 0x000389, "Member 'QuestNotification_C_ExecuteUbergraph_QuestNotification::CallFunc_PlayAnimationByName_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(QuestNotification_C_ExecuteUbergraph_QuestNotification, CallFunc_Divide_DoubleDouble_ReturnValue_1) == 0x000390, "Member 'QuestNotification_C_ExecuteUbergraph_QuestNotification::CallFunc_Divide_DoubleDouble_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(QuestNotification_C_ExecuteUbergraph_QuestNotification, CallFunc_SetScalarParameterValue_Value_ImplicitCast) == 0x000398, "Member 'QuestNotification_C_ExecuteUbergraph_QuestNotification::CallFunc_SetScalarParameterValue_Value_ImplicitCast' has a wrong offset!");
static_assert(offsetof(QuestNotification_C_ExecuteUbergraph_QuestNotification, CallFunc_SetScalarParameterValue_Value_ImplicitCast_1) == 0x00039C, "Member 'QuestNotification_C_ExecuteUbergraph_QuestNotification::CallFunc_SetScalarParameterValue_Value_ImplicitCast_1' has a wrong offset!");
static_assert(offsetof(QuestNotification_C_ExecuteUbergraph_QuestNotification, CallFunc_FMax_A_ImplicitCast) == 0x0003A0, "Member 'QuestNotification_C_ExecuteUbergraph_QuestNotification::CallFunc_FMax_A_ImplicitCast' has a wrong offset!");
static_assert(offsetof(QuestNotification_C_ExecuteUbergraph_QuestNotification, CallFunc_PlayAnimationByName_Speed_ImplicitCast) == 0x0003A8, "Member 'QuestNotification_C_ExecuteUbergraph_QuestNotification::CallFunc_PlayAnimationByName_Speed_ImplicitCast' has a wrong offset!");
static_assert(offsetof(QuestNotification_C_ExecuteUbergraph_QuestNotification, CallFunc_PlayAnimation_PlaybackSpeed_ImplicitCast) == 0x0003AC, "Member 'QuestNotification_C_ExecuteUbergraph_QuestNotification::CallFunc_PlayAnimation_PlaybackSpeed_ImplicitCast' has a wrong offset!");
static_assert(offsetof(QuestNotification_C_ExecuteUbergraph_QuestNotification, CallFunc_SetWidthOverride_InWidthOverride_ImplicitCast) == 0x0003B0, "Member 'QuestNotification_C_ExecuteUbergraph_QuestNotification::CallFunc_SetWidthOverride_InWidthOverride_ImplicitCast' has a wrong offset!");
static_assert(offsetof(QuestNotification_C_ExecuteUbergraph_QuestNotification, CallFunc_Divide_DoubleDouble_A_ImplicitCast) == 0x0003B8, "Member 'QuestNotification_C_ExecuteUbergraph_QuestNotification::CallFunc_Divide_DoubleDouble_A_ImplicitCast' has a wrong offset!");
static_assert(offsetof(QuestNotification_C_ExecuteUbergraph_QuestNotification, CallFunc_RetriggerableDelay_Duration_ImplicitCast) == 0x0003C0, "Member 'QuestNotification_C_ExecuteUbergraph_QuestNotification::CallFunc_RetriggerableDelay_Duration_ImplicitCast' has a wrong offset!");

// Function QuestNotification.QuestNotification_C.LoadMaterial
// 0x0020 (0x0020 - 0x0000)
struct QuestNotification_C_LoadMaterial final
{
public:
	TSoftObjectPtr<class UMaterialInterface>      SoftMaterial;                                      // 0x0000(0x0020)(BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)
};
static_assert(alignof(QuestNotification_C_LoadMaterial) == 0x000008, "Wrong alignment on QuestNotification_C_LoadMaterial");
static_assert(sizeof(QuestNotification_C_LoadMaterial) == 0x000020, "Wrong size on QuestNotification_C_LoadMaterial");
static_assert(offsetof(QuestNotification_C_LoadMaterial, SoftMaterial) == 0x000000, "Member 'QuestNotification_C_LoadMaterial::SoftMaterial' has a wrong offset!");

// Function QuestNotification.QuestNotification_C.LoadTextureForDefaultMaterial
// 0x0020 (0x0020 - 0x0000)
struct QuestNotification_C_LoadTextureForDefaultMaterial final
{
public:
	TSoftObjectPtr<class UObject>                 Asset;                                             // 0x0000(0x0020)(BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)
};
static_assert(alignof(QuestNotification_C_LoadTextureForDefaultMaterial) == 0x000008, "Wrong alignment on QuestNotification_C_LoadTextureForDefaultMaterial");
static_assert(sizeof(QuestNotification_C_LoadTextureForDefaultMaterial) == 0x000020, "Wrong size on QuestNotification_C_LoadTextureForDefaultMaterial");
static_assert(offsetof(QuestNotification_C_LoadTextureForDefaultMaterial, Asset) == 0x000000, "Member 'QuestNotification_C_LoadTextureForDefaultMaterial::Asset' has a wrong offset!");

// Function QuestNotification.QuestNotification_C.OnEnableCompleteFlavorText
// 0x0001 (0x0001 - 0x0000)
struct QuestNotification_C_OnEnableCompleteFlavorText final
{
public:
	bool                                          IsEnabled;                                         // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(QuestNotification_C_OnEnableCompleteFlavorText) == 0x000001, "Wrong alignment on QuestNotification_C_OnEnableCompleteFlavorText");
static_assert(sizeof(QuestNotification_C_OnEnableCompleteFlavorText) == 0x000001, "Wrong size on QuestNotification_C_OnEnableCompleteFlavorText");
static_assert(offsetof(QuestNotification_C_OnEnableCompleteFlavorText, IsEnabled) == 0x000000, "Member 'QuestNotification_C_OnEnableCompleteFlavorText::IsEnabled' has a wrong offset!");

// Function QuestNotification.QuestNotification_C.OnLoaded_3102A2CF412705C565D4AEA743125398
// 0x0008 (0x0008 - 0x0000)
struct QuestNotification_C_OnLoaded_3102A2CF412705C565D4AEA743125398 final
{
public:
	class UObject*                                Loaded;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(QuestNotification_C_OnLoaded_3102A2CF412705C565D4AEA743125398) == 0x000008, "Wrong alignment on QuestNotification_C_OnLoaded_3102A2CF412705C565D4AEA743125398");
static_assert(sizeof(QuestNotification_C_OnLoaded_3102A2CF412705C565D4AEA743125398) == 0x000008, "Wrong size on QuestNotification_C_OnLoaded_3102A2CF412705C565D4AEA743125398");
static_assert(offsetof(QuestNotification_C_OnLoaded_3102A2CF412705C565D4AEA743125398, Loaded) == 0x000000, "Member 'QuestNotification_C_OnLoaded_3102A2CF412705C565D4AEA743125398::Loaded' has a wrong offset!");

// Function QuestNotification.QuestNotification_C.OnLoaded_5531D17F479B14E7EA1B2E81CC00B2AD
// 0x0008 (0x0008 - 0x0000)
struct QuestNotification_C_OnLoaded_5531D17F479B14E7EA1B2E81CC00B2AD final
{
public:
	class UObject*                                Loaded;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(QuestNotification_C_OnLoaded_5531D17F479B14E7EA1B2E81CC00B2AD) == 0x000008, "Wrong alignment on QuestNotification_C_OnLoaded_5531D17F479B14E7EA1B2E81CC00B2AD");
static_assert(sizeof(QuestNotification_C_OnLoaded_5531D17F479B14E7EA1B2E81CC00B2AD) == 0x000008, "Wrong size on QuestNotification_C_OnLoaded_5531D17F479B14E7EA1B2E81CC00B2AD");
static_assert(offsetof(QuestNotification_C_OnLoaded_5531D17F479B14E7EA1B2E81CC00B2AD, Loaded) == 0x000000, "Member 'QuestNotification_C_OnLoaded_5531D17F479B14E7EA1B2E81CC00B2AD::Loaded' has a wrong offset!");

// Function QuestNotification.QuestNotification_C.OnPlayRushedNotificationIntro
// 0x0004 (0x0004 - 0x0000)
struct QuestNotification_C_OnPlayRushedNotificationIntro final
{
public:
	float                                         Rate;                                              // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(QuestNotification_C_OnPlayRushedNotificationIntro) == 0x000004, "Wrong alignment on QuestNotification_C_OnPlayRushedNotificationIntro");
static_assert(sizeof(QuestNotification_C_OnPlayRushedNotificationIntro) == 0x000004, "Wrong size on QuestNotification_C_OnPlayRushedNotificationIntro");
static_assert(offsetof(QuestNotification_C_OnPlayRushedNotificationIntro, Rate) == 0x000000, "Member 'QuestNotification_C_OnPlayRushedNotificationIntro::Rate' has a wrong offset!");

// Function QuestNotification.QuestNotification_C.OnUpdateNotificationBackground
// 0x0028 (0x0028 - 0x0000)
struct QuestNotification_C_OnUpdateNotificationBackground final
{
public:
	TSoftObjectPtr<class UObject>                 AssetToDisplay;                                    // 0x0000(0x0020)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, UObjectWrapper, HasGetValueTypeHash)
	bool                                          bUseRarityContainer;                               // 0x0020(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          bIsDailyPunchcardQuest;                            // 0x0021(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(QuestNotification_C_OnUpdateNotificationBackground) == 0x000008, "Wrong alignment on QuestNotification_C_OnUpdateNotificationBackground");
static_assert(sizeof(QuestNotification_C_OnUpdateNotificationBackground) == 0x000028, "Wrong size on QuestNotification_C_OnUpdateNotificationBackground");
static_assert(offsetof(QuestNotification_C_OnUpdateNotificationBackground, AssetToDisplay) == 0x000000, "Member 'QuestNotification_C_OnUpdateNotificationBackground::AssetToDisplay' has a wrong offset!");
static_assert(offsetof(QuestNotification_C_OnUpdateNotificationBackground, bUseRarityContainer) == 0x000020, "Member 'QuestNotification_C_OnUpdateNotificationBackground::bUseRarityContainer' has a wrong offset!");
static_assert(offsetof(QuestNotification_C_OnUpdateNotificationBackground, bIsDailyPunchcardQuest) == 0x000021, "Member 'QuestNotification_C_OnUpdateNotificationBackground::bIsDailyPunchcardQuest' has a wrong offset!");

// Function QuestNotification.QuestNotification_C.PreConstruct
// 0x0001 (0x0001 - 0x0000)
struct QuestNotification_C_PreConstruct final
{
public:
	bool                                          IsDesignTime;                                      // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(QuestNotification_C_PreConstruct) == 0x000001, "Wrong alignment on QuestNotification_C_PreConstruct");
static_assert(sizeof(QuestNotification_C_PreConstruct) == 0x000001, "Wrong size on QuestNotification_C_PreConstruct");
static_assert(offsetof(QuestNotification_C_PreConstruct, IsDesignTime) == 0x000000, "Member 'QuestNotification_C_PreConstruct::IsDesignTime' has a wrong offset!");

// Function QuestNotification.QuestNotification_C.SetAssistData
// 0x0018 (0x0018 - 0x0000)
struct QuestNotification_C_SetAssistData final
{
public:
	bool                                          bWasAssisted;                                      // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 OtherPlayersName;                                  // 0x0008(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
};
static_assert(alignof(QuestNotification_C_SetAssistData) == 0x000008, "Wrong alignment on QuestNotification_C_SetAssistData");
static_assert(sizeof(QuestNotification_C_SetAssistData) == 0x000018, "Wrong size on QuestNotification_C_SetAssistData");
static_assert(offsetof(QuestNotification_C_SetAssistData, bWasAssisted) == 0x000000, "Member 'QuestNotification_C_SetAssistData::bWasAssisted' has a wrong offset!");
static_assert(offsetof(QuestNotification_C_SetAssistData, OtherPlayersName) == 0x000008, "Member 'QuestNotification_C_SetAssistData::OtherPlayersName' has a wrong offset!");

// Function QuestNotification.QuestNotification_C.SetIconParameters
// 0x0008 (0x0008 - 0x0000)
struct QuestNotification_C_SetIconParameters final
{
public:
	class UMaterialInstanceDynamic*               CallFunc_GetDynamicMaterial_ReturnValue;           // 0x0000(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(QuestNotification_C_SetIconParameters) == 0x000008, "Wrong alignment on QuestNotification_C_SetIconParameters");
static_assert(sizeof(QuestNotification_C_SetIconParameters) == 0x000008, "Wrong size on QuestNotification_C_SetIconParameters");
static_assert(offsetof(QuestNotification_C_SetIconParameters, CallFunc_GetDynamicMaterial_ReturnValue) == 0x000000, "Member 'QuestNotification_C_SetIconParameters::CallFunc_GetDynamicMaterial_ReturnValue' has a wrong offset!");

// Function QuestNotification.QuestNotification_C.UpdateProgress
// 0x0050 (0x0050 - 0x0000)
struct QuestNotification_C_UpdateProgress final
{
public:
	int32                                         CallFunc_Max_ReturnValue;                          // 0x0000(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Max_ReturnValue_1;                        // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Conv_IntToDouble_ReturnValue;             // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Conv_IntToDouble_ReturnValue_1;           // 0x0010(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Conv_IntToDouble_ReturnValue_2;           // 0x0018(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Conv_IntToDouble_ReturnValue_3;           // 0x0020(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Divide_DoubleDouble_ReturnValue;          // 0x0028(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Divide_DoubleDouble_ReturnValue_1;        // 0x0030(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UUMGSequencePlayer*                     CallFunc_PlayAnimation_ReturnValue;                // 0x0038(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UMaterialInstanceDynamic*               CallFunc_GetDynamicMaterial_ReturnValue;           // 0x0040(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_SetScalarParameterValue_Value_ImplicitCast; // 0x0048(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_SetScalarParameterValue_Value_ImplicitCast_1; // 0x004C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(QuestNotification_C_UpdateProgress) == 0x000008, "Wrong alignment on QuestNotification_C_UpdateProgress");
static_assert(sizeof(QuestNotification_C_UpdateProgress) == 0x000050, "Wrong size on QuestNotification_C_UpdateProgress");
static_assert(offsetof(QuestNotification_C_UpdateProgress, CallFunc_Max_ReturnValue) == 0x000000, "Member 'QuestNotification_C_UpdateProgress::CallFunc_Max_ReturnValue' has a wrong offset!");
static_assert(offsetof(QuestNotification_C_UpdateProgress, CallFunc_Max_ReturnValue_1) == 0x000004, "Member 'QuestNotification_C_UpdateProgress::CallFunc_Max_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(QuestNotification_C_UpdateProgress, CallFunc_Conv_IntToDouble_ReturnValue) == 0x000008, "Member 'QuestNotification_C_UpdateProgress::CallFunc_Conv_IntToDouble_ReturnValue' has a wrong offset!");
static_assert(offsetof(QuestNotification_C_UpdateProgress, CallFunc_Conv_IntToDouble_ReturnValue_1) == 0x000010, "Member 'QuestNotification_C_UpdateProgress::CallFunc_Conv_IntToDouble_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(QuestNotification_C_UpdateProgress, CallFunc_Conv_IntToDouble_ReturnValue_2) == 0x000018, "Member 'QuestNotification_C_UpdateProgress::CallFunc_Conv_IntToDouble_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(QuestNotification_C_UpdateProgress, CallFunc_Conv_IntToDouble_ReturnValue_3) == 0x000020, "Member 'QuestNotification_C_UpdateProgress::CallFunc_Conv_IntToDouble_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(QuestNotification_C_UpdateProgress, CallFunc_Divide_DoubleDouble_ReturnValue) == 0x000028, "Member 'QuestNotification_C_UpdateProgress::CallFunc_Divide_DoubleDouble_ReturnValue' has a wrong offset!");
static_assert(offsetof(QuestNotification_C_UpdateProgress, CallFunc_Divide_DoubleDouble_ReturnValue_1) == 0x000030, "Member 'QuestNotification_C_UpdateProgress::CallFunc_Divide_DoubleDouble_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(QuestNotification_C_UpdateProgress, CallFunc_PlayAnimation_ReturnValue) == 0x000038, "Member 'QuestNotification_C_UpdateProgress::CallFunc_PlayAnimation_ReturnValue' has a wrong offset!");
static_assert(offsetof(QuestNotification_C_UpdateProgress, CallFunc_GetDynamicMaterial_ReturnValue) == 0x000040, "Member 'QuestNotification_C_UpdateProgress::CallFunc_GetDynamicMaterial_ReturnValue' has a wrong offset!");
static_assert(offsetof(QuestNotification_C_UpdateProgress, CallFunc_SetScalarParameterValue_Value_ImplicitCast) == 0x000048, "Member 'QuestNotification_C_UpdateProgress::CallFunc_SetScalarParameterValue_Value_ImplicitCast' has a wrong offset!");
static_assert(offsetof(QuestNotification_C_UpdateProgress, CallFunc_SetScalarParameterValue_Value_ImplicitCast_1) == 0x00004C, "Member 'QuestNotification_C_UpdateProgress::CallFunc_SetScalarParameterValue_Value_ImplicitCast_1' has a wrong offset!");

}

