#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WaterAdvanced

#include "Basic.hpp"

#include "WaterAdvanced_classes.hpp"
#include "WaterAdvanced_parameters.hpp"


namespace SDK
{

// Function WaterAdvanced.ShallowWaterSubsystem.OnLocalPlayerControllerBecomesValid
// (Final, Native, Private)
// Parameters:
// class APlayerController*                InPlayerController                                     (Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UShallowWaterSubsystem::OnLocalPlayerControllerBecomesValid(class APlayerController* InPlayerController)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ShallowWaterSubsystem", "OnLocalPlayerControllerBecomesValid");

	Params::ShallowWaterSubsystem_OnLocalPlayerControllerBecomesValid Parms{};

	Parms.InPlayerController = InPlayerController;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function WaterAdvanced.ShallowWaterSubsystem.OnLocalPlayerPawnBecomesValid
// (Final, Native, Private)
// Parameters:
// class APawn*                            OldPawn                                                (Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class APawn*                            NewPawn                                                (Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UShallowWaterSubsystem::OnLocalPlayerPawnBecomesValid(class APawn* OldPawn, class APawn* NewPawn)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ShallowWaterSubsystem", "OnLocalPlayerPawnBecomesValid");

	Params::ShallowWaterSubsystem_OnLocalPlayerPawnBecomesValid Parms{};

	Parms.OldPawn = OldPawn;
	Parms.NewPawn = NewPawn;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function WaterAdvanced.ShallowWaterSubsystem.OnWaterInfoTextureCreatedOrChanged
// (Final, Native, Protected)
// Parameters:
// class UTextureRenderTarget2D*           WaterInfoTexture_0                                     (ConstParm, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UShallowWaterSubsystem::OnWaterInfoTextureCreatedOrChanged(const class UTextureRenderTarget2D* WaterInfoTexture_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ShallowWaterSubsystem", "OnWaterInfoTextureCreatedOrChanged");

	Params::ShallowWaterSubsystem_OnWaterInfoTextureCreatedOrChanged Parms{};

	Parms.WaterInfoTexture_0 = WaterInfoTexture_0;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function WaterAdvanced.ShallowWaterSubsystem.RegisterImpact
// (Final, Native, Public, HasDefaults, BlueprintCallable)
// Parameters:
// struct FVector                          ImpactPosition                                         (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// struct FVector                          ImpactVelocity                                         (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// float                                   ImpactRadius                                           (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UShallowWaterSubsystem::RegisterImpact(const struct FVector& ImpactPosition, const struct FVector& ImpactVelocity, float ImpactRadius)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ShallowWaterSubsystem", "RegisterImpact");

	Params::ShallowWaterSubsystem_RegisterImpact Parms{};

	Parms.ImpactPosition = std::move(ImpactPosition);
	Parms.ImpactVelocity = std::move(ImpactVelocity);
	Parms.ImpactRadius = ImpactRadius;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function WaterAdvanced.ShallowWaterSubsystem.ResetImpacts
// (Final, Native, Public, BlueprintCallable)

void UShallowWaterSubsystem::ResetImpacts()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ShallowWaterSubsystem", "ResetImpacts");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function WaterAdvanced.ShallowWaterSubsystem.SetRecentValidWaterBody
// (Final, Native, Protected, BlueprintCallable)
// Parameters:
// class AWaterBody*                       InWaterBody                                            (Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool                                    bOnlyReplaceIfNoValidWaterBodyFound                    (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

bool UShallowWaterSubsystem::SetRecentValidWaterBody(class AWaterBody* InWaterBody, bool bOnlyReplaceIfNoValidWaterBodyFound)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ShallowWaterSubsystem", "SetRecentValidWaterBody");

	Params::ShallowWaterSubsystem_SetRecentValidWaterBody Parms{};

	Parms.InWaterBody = InWaterBody;
	Parms.bOnlyReplaceIfNoValidWaterBodyFound = bOnlyReplaceIfNoValidWaterBodyFound;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function WaterAdvanced.ShallowWaterSubsystem.GetCurrentWaterBody
// (Native, Protected, BlueprintCallable, BlueprintPure, Const)
// Parameters:
// class AWaterBody*                       ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

class AWaterBody* UShallowWaterSubsystem::GetCurrentWaterBody() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ShallowWaterSubsystem", "GetCurrentWaterBody");

	Params::ShallowWaterSubsystem_GetCurrentWaterBody Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function WaterAdvanced.ShallowWaterSubsystem.GetRecentValidWaterBody
// (Final, Native, Protected, BlueprintCallable, BlueprintPure, Const)
// Parameters:
// class AWaterBody*                       ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

class AWaterBody* UShallowWaterSubsystem::GetRecentValidWaterBody() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ShallowWaterSubsystem", "GetRecentValidWaterBody");

	Params::ShallowWaterSubsystem_GetRecentValidWaterBody Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}

}

